[package]
name = "account_socket"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
warp = { version = "0.4", features = ["server"] }
anyhow = "1.0.100"
async-trait = "0.1.89"
async-tungstenite = "0.31.0"
env_logger = "0.11.8"
serde_json = "1.0.145"
yellowstone-grpc-client = "9.0.0"
dotenv = "0.15.0"
